### ISSUE TITLE
Google Drive link not available

### ISSUE THREAD

**Issue by Wangjii** [VietHoang1710/EmoRecCom#13]
I'm sorry to bother you.
When I try to run the code for this repository, I see that the download of the dataset times out.
Could you please check if the link is valid.
Thanks.

**Comment by VietHoang1512** [comment]
Hi @Wangjii, since I cannot distribute the dataset without permission from the competition organizer, this is the description from the [official competition site](https://competitions.codalab.org/competitions/27884#learn_the_details), you can easily rename and format the directory to adapt with the code, please feel free to ask further questions if any

> Emotions
> 
> There are 8 emotion classes including: 0=Angry, 1=Disgust, 2=Fear, 3=Happy, 4=Sad, 5=Surprise, 6=Neutral, 7=Others.
> 
> Data Format
> 
> Each instance includes 10 fields as follows:
> 
> id: id of the image in the corresponding set (train or test)
> 
> image_id: image_id associated with the image name
> 
> emotion0_label: a manually annotated label for emotion0.
> 
> emotion1_label: a manually annotated label for emotion1.
> 
> emotion2_label: a manually annotated label for emotion2.
> 
> emotion3_label: a manually annotated label for emotion3.
> 
> emotion4_label: a manually annotated label for emotion4.
> 
> emotion5_label: a manually annotated label for emotion5.
> 
> emotion6_label: a manually annotated label for emotion6.
> 
> emotion7_label: a manually annotated label for emotion7.
> 
> Training/Testing Data (Available on Jan 10, 2021)
> 
> Link download: http://bit.ly/emoregcom-public-training
> Note: participants are provided 6,112 training examples with the respective annotated labels. The testing set consists of 2046 examples without labels.
> Data format:
> `train_transcriptions.json`: contains auto-transcriptions in comic scenes
> `train` contains 6,112 raw images of training data
> `train_emotion_labels.csv`: contains binary labels
> `additional_infor:emotion_polarity.csv`: contains additional info, the polarities of emotions in (0,1). Participants are encouraged to leverage this additional resources to achieve better performace.
> `test`: contains 2,046 raw images of testing data
> `test_transcriptions.json` contains auto-transcriptions in comic scenes
> Submission file:
> File `results.zip` contains a submission sample. Please strictly follow the name convention and format of the csv file. Generally, your file needs to have 10 columns (without headers): id,image_id,angry,disgust,fear,happy,sad,surprise,neutral,other.
>  Private Test Data (Available on March 24, 2021)
> 
> Link download:  http://bit.ly/emoreccom-private-test
> Note: participants are provided 2,041 examples without labels.
> Data format:
> `transcriptions.json`: contains auto-transcriptions in comic scenes
> `images` contains 2,041 raw images of test data
> Submission file:
> File `results.zip` contains a submission sample. Please strictly follow the name convention and format of the csv file. Generally, your file needs to have 10 columns (without headers): id,image_id,angry,disgust,fear,happy,sad,surprise,neutral,other.

**Comment by Wangjii** [comment]
Thank you for your reply!
I have run the program successfully.
